### ISSUE TITLE
Configure API

### ISSUE THREAD

**Issue by naicampbell** [Btayloragent/Conscience-Cosmetics#6]

**Comment by EliasIsaiah** [comment]
this can be multiple issues:
## issue 1: create boilerplate express api with /test GET endpoint that returns "hello world"
resources:
* https://dev.to/bilal1718/how-to-create-a-backend-api-in-express-js-e0k

## issue 2: determine all of the api endpoints that you need
* GET product details
* POST add a favorite to the database
* PUT update star rating

**Comment by Btayloragent** [comment]
Adding api for videos first using PexelAPI
